[package]
name = "crocodile"
version = "0.1.0"
authors = ["Elias.Yao <siran0611@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "crocodiledb",
    "components/app",
    "components/admin",
    "components/error",
    "components/metrics",
    "components/raft",
    "components/signal",
    "components/sql",
    "components/storage",
    "components/tracing",
    "components/utils",
    "components/transaction",
    "components/log",
]

[profile.dev]
debug = false
[profile.test]
debug = false