[package]
name = "crocodile"
version = "0.1.0"
authors = ["Elias.Yao <siran0611@gmail.com>"]
edition = "2018"

[dependencies]
http = "0.2"
rand = "0.7"
bytes = "1.0.1"
crossbeam-channel = "0.5.0"
thiserror = "1.0"
farmhash = "1.1"
prost = "0.7"
enum_dispatch = "0.3"
crc = "1.8"
serde = "~1.0.91"
serde_derive = "~1.0.91"
serde_json = "1"
bincode = "~1.3.1"
hyper = { version = "0.14.2", features = ["http1", "http2", "client", "server"] }
tokio = { version = "1", features = ["macros", "sync", "parking_lot","signal"] }
futures = "0.3.9"
deflate = { version = "0.7.18", features = ["gzip"] }
tracing = "0.1.23"
tokio-trace = { git = "https://github.com/hawkw/tokio-trace", rev = "7d5998e7cb3beb06ada5983675319dc4853576c5", features = ["serde"] }
html-escape = "0.2.5"
memmap = "0.7"
priority-queue = "1.1.0"


[dependencies.tower]
version = "0.4"
# disable tower's tracing `log` integration for performance reasons, since we
# will consume tower's traces as traces.
default-features = false
features = [
    "buffer",
    "make",
    "spawn-ready",
    "timeout",
    "util",
]

[dependencies.tracing-subscriber]
version = "0.2.16"
# we don't need `chrono` time formatting or ANSI colored output
default-features = false
features = ["env-filter", "fmt", "smallvec", "tracing-log", "json", "parking_lot"]

[dev-dependencies]
yatp = { git = "https://github.com/tikv/yatp.git" }
criterion = "0.3"
pretty_assertions = "~0.6.1"