[package]
name = "crocodile"
version = "0.1.0"
authors = ["Elias.Yao <siran0611@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
bytes = "1.0.1"
crossbeam-channel = "0.5.0"
thiserror = "1.0"
farmhash = "1.1"
prost = "0.7"
enum_dispatch = "0.3"
crc = "1.8"
serde = "~1.0.91"
serde_derive = "~1.0.91"
bincode = "~1.3.1"


[dev-dependencies]
yatp = { git = "https://github.com/tikv/yatp.git" }
criterion = "0.3.3"


[[bench]]
name = "lsm"
path = "benches/lsm.rs"
harness = false
